import type {Metadata} from "next";
import {DM_Sans} from "next/font/google";
import "./globals.css";
import {NuqsAdapter} from "nuqs/adapters/next/app";

import {TRPCReactProvider} from "@/trpc/client";
import {Toaster} from "sonner";

const dm_sans = DM_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${dm_sans.variable} ${dm_sans.variable} antialiased`}>
        <NuqsAdapter>
          <TRPCReactProvider>
            <Toaster />
            {children}
          </TRPCReactProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
